### ISSUE TITLE
Firmware issue?

### ISSUE THREAD

**Issue by bjablonskipwr** [sandeepmistry/node-bbc-microbit#11] opened 2017-01-25 21:39 UTC
Great library - thanks for creating this!

I'm trying out examples for the start. I've started with accelerometer-service.js for the start. It seems that microbit get disconnected as soon as the "Draw a circle" procedure finishes on the device. Is it some firmware issue or bluetooth stack problem?

**Comment by bluetooth-mdw** [comment] 2017-01-26 06:02
It's not a Bluetooth stack problem.

**Comment by bluetooth-mdw** [comment] 2017-01-27 09:12
I think this is a bug in the micro:bit's "DAL" i.e. Device Abstraction Layer. I've discussed with Lancaster University, who own the DAL and submitted an issue:

https://github.com/lancaster-university/microbit-dal/issues/262

**Comment by sandeepmistry** [comment] 2017-01-30 01:55
@bjablonskipwr I think I had similar issues.

I had to calibrate the magnetometer right after flashing the firmware or things would be flaky connection wise. This is noted in the read me.

Closing this for now, as the issue is reported upstream.

**Closed by sandeepmistry** 2017-01-30 01:55 UTC
